version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - mynet
    volumes: 
      - ./db_out:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    build: .
    # depends_on:
    #   - db
    ports:
      - 5000:5000
    # environment:
    #   NODE_ENV: production
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_NAME: postgres
    networks:
      - mynet
networks:
  mynet:
    driver:
      bridge
